language: python

matrix:
    include:
        - "3.3"
        - "3.4"
        - "3.5"
        - "3.6"

services:
    - postgresql
    - mysql

before_script:
    - psql -U postgres < tests/travis/postgre.sql
    - mysql --user=root --password=''  < tests/travis/my.sql

install:
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt
    - python setup.py install

script:
    - flake8
    - py.test tests/
