language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

services:
    - postgresql

before_script:
    - psql -c 'CREATE DATABASE tornado_sqlalchemy;' -U postgres

install:
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt

script:
    - flake8
