language: python

matrix:
    include:
        - python: "2.7"
          env: REQUIREMENTS="requirements/2.txt"
        - python: "3.3"
          env: REQUIREMENTS="requirements/3.txt"
        - python: "3.4"
          env: REQUIREMENTS="requirements/3.txt"
        - python: "3.5"
          env: REQUIREMENTS="requirements/3.txt"
        - python: "3.6"
          env: REQUIREMENTS="requirements/3.txt"

services:
    - postgresql
    - mysql

before_script:
    - psql -U postgres < tests/travis/postgre.sql
    - mysql --user=root --password=''  < tests/travis/my.sql

install:
    - pip install --upgrade pip setuptools
    - pip install -r $REQUIREMENTS
    - python setup.py install

script:
    - flake8
    - py.test tests/
